# Generated by Django 4.1.5 on 2023-01-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
